name: Deploy CI Role

on:
  workflow_call:
    inputs:
      aws_account_id:
        description: 'AWS Account ID'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        type: string
      working_directory:
        description: 'Terragrunt working directory'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy-ci-role:
    name: Bootstrap Project CI Role
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.14.3

      - name: Install Terragrunt
        run: |
          TG_VERSION=v1.0.1
          wget https://github.com/gruntwork-io/terragrunt/releases/download/$TG_VERSION/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Assume Bootstrap Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/ml-platform-github-ci-bootstrap-role
          aws-region: ${{ inputs.aws_region }}

      - name: Terragrunt Init (Bootstrap)
        working-directory: ${{ inputs.working_directory }}
        run: terragrunt init

      - name: Terragrunt Apply (Bootstrap)
        working-directory: ${{ inputs.working_directory }}
        run: terragrunt apply -auto-approve
